from pydantic import BaseModel, ConfigDict, Field
from typing import Optional, Literal

class ClientData(BaseModel):

    # On interdit formellement tout champ non déclaré dans ce fichier pour refuser les requêtes avec des données en plus
    model_config = ConfigDict(extra="forbid")

    # --- Variables de contrôle (MLOps) ---
    SK_ID_CURR: Optional[int] = Field(default=None, description="ID du client")
    is_test: bool = Field(default=False, description="Flag pour les tests")

    # ==========================================
    # VARIABLES OBLIGATOIRES (0% manquantes)
    # ==========================================
    
    # Catégorielles Strictes
    NAME_CONTRACT_TYPE: Literal["Cash loans", "Revolving loans"] = Field(...)
    CODE_GENDER: Literal["M", "F", "XNA"] = Field(...)
    FLAG_OWN_CAR: Literal["N", "Y"] = Field(...)
    FLAG_OWN_REALTY: Literal["Y", "N"] = Field(...)
    NAME_INCOME_TYPE: Literal["Working", "State servant", "Commercial associate", "Pensioner", "Unemployed", "Student", "Businessman", "Maternity leave"] = Field(...)
    NAME_EDUCATION_TYPE: Literal["Secondary / secondary special", "Higher education", "Incomplete higher", "Lower secondary", "Academic degree"] = Field(...)
    NAME_FAMILY_STATUS: Literal["Single / not married", "Married", "Civil marriage", "Widow", "Separated", "Unknown"] = Field(...)
    NAME_HOUSING_TYPE: Literal["House / apartment", "Rented apartment", "With parents", "Municipal apartment", "Office apartment", "Co-op apartment"] = Field(...)
    WEEKDAY_APPR_PROCESS_START: Literal["WEDNESDAY", "MONDAY", "THURSDAY", "SUNDAY", "SATURDAY", "FRIDAY", "TUESDAY"] = Field(...)
    ORGANIZATION_TYPE: Literal["Business Entity Type 3", "School", "Government", "Religion", "Other", "XNA", "Electricity", "Medicine", "Business Entity Type 2", "Self-employed", "Transport: type 2", "Construction", "Housing", "Kindergarten", "Trade: type 7", "Industry: type 11", "Military", "Services", "Security Ministries", "Transport: type 4", "Industry: type 1", "Emergency", "Security", "Trade: type 2", "University", "Transport: type 3", "Police", "Business Entity Type 1", "Postal", "Industry: type 4", "Agriculture", "Restaurant", "Culture", "Hotel", "Industry: type 7", "Trade: type 3", "Industry: type 3", "Bank", "Industry: type 9", "Insurance", "Trade: type 6", "Industry: type 2", "Transport: type 1", "Industry: type 12", "Mobile", "Trade: type 1", "Industry: type 5", "Industry: type 10", "Legal Services", "Advertising", "Trade: type 5", "Cleaning", "Industry: type 13", "Trade: type 4", "Telecom", "Industry: type 8", "Realtor", "Industry: type 6"] = Field(...)

    # Numériques Strictes (avec règles de signes)
    CNT_CHILDREN: int = Field(..., ge=0)
    AMT_INCOME_TOTAL: float = Field(..., ge=0)
    AMT_CREDIT: float = Field(..., ge=0)
    AMT_ANNUITY: float = Field(..., ge=0)
    REGION_POPULATION_RELATIVE: float = Field(..., ge=0)
    DAYS_BIRTH: int = Field(..., le=0)
    DAYS_EMPLOYED: int = Field(...)  # Peut être positif ou négatif
    DAYS_REGISTRATION: float = Field(..., le=0)
    DAYS_ID_PUBLISH: int = Field(..., le=0)
    DAYS_LAST_PHONE_CHANGE: float = Field(..., le=0)
    FLAG_MOBIL: int = Field(..., ge=0)
    FLAG_EMP_PHONE: int = Field(..., ge=0)
    FLAG_WORK_PHONE: int = Field(..., ge=0)
    FLAG_CONT_MOBILE: int = Field(..., ge=0)
    FLAG_PHONE: int = Field(..., ge=0)
    FLAG_EMAIL: int = Field(..., ge=0)
    CNT_FAM_MEMBERS: float = Field(..., ge=0)
    REGION_RATING_CLIENT: int = Field(..., ge=0)
    REGION_RATING_CLIENT_W_CITY: int = Field(..., ge=0)
    HOUR_APPR_PROCESS_START: int = Field(..., ge=0)
    REG_REGION_NOT_LIVE_REGION: int = Field(..., ge=0)
    REG_REGION_NOT_WORK_REGION: int = Field(..., ge=0)
    LIVE_REGION_NOT_WORK_REGION: int = Field(..., ge=0)
    REG_CITY_NOT_LIVE_CITY: int = Field(..., ge=0)
    REG_CITY_NOT_WORK_CITY: int = Field(..., ge=0)
    LIVE_CITY_NOT_WORK_CITY: int = Field(..., ge=0)
    FLAG_DOCUMENT_2: int = Field(..., ge=0)
    FLAG_DOCUMENT_3: int = Field(..., ge=0)
    FLAG_DOCUMENT_4: int = Field(..., ge=0)
    FLAG_DOCUMENT_5: int = Field(..., ge=0)
    FLAG_DOCUMENT_6: int = Field(..., ge=0)
    FLAG_DOCUMENT_7: int = Field(..., ge=0)
    FLAG_DOCUMENT_8: int = Field(..., ge=0)
    FLAG_DOCUMENT_9: int = Field(..., ge=0)
    FLAG_DOCUMENT_10: int = Field(..., ge=0)
    FLAG_DOCUMENT_11: int = Field(..., ge=0)
    FLAG_DOCUMENT_12: int = Field(..., ge=0)
    FLAG_DOCUMENT_13: int = Field(..., ge=0)
    FLAG_DOCUMENT_14: int = Field(..., ge=0)
    FLAG_DOCUMENT_15: int = Field(..., ge=0)
    FLAG_DOCUMENT_16: int = Field(..., ge=0)
    FLAG_DOCUMENT_17: int = Field(..., ge=0)
    FLAG_DOCUMENT_18: int = Field(..., ge=0)
    FLAG_DOCUMENT_19: int = Field(..., ge=0)
    FLAG_DOCUMENT_20: int = Field(..., ge=0)
    FLAG_DOCUMENT_21: int = Field(..., ge=0)

    # ==========================================
    # VARIABLES OPTIONNELLES (>0% manquantes)
    # ==========================================
    
    # Catégorielles Optionnelles
    NAME_TYPE_SUITE: Optional[Literal["Unaccompanied", "Family", "Spouse, partner", "Children", "Other_A", "Other_B", "Group of people"]] = Field(default=None)
    OCCUPATION_TYPE: Optional[Literal["Laborers", "Core staff", "Accountants", "Managers", "Drivers", "Sales staff", "Cleaning staff", "Cooking staff", "Private service staff", "Medicine staff", "Security staff", "High skill tech staff", "Waiters/barmen staff", "Low-skill Laborers", "Realty agents", "Secretaries", "IT staff", "HR staff"]] = Field(default=None)
    FONDKAPREMONT_MODE: Optional[Literal["reg oper account", "org spec account", "reg oper spec account", "not specified"]] = Field(default=None)
    HOUSETYPE_MODE: Optional[Literal["block of flats", "terraced house", "specific housing"]] = Field(default=None)
    WALLSMATERIAL_MODE: Optional[Literal["Stone, brick", "Block", "Panel", "Mixed", "Wooden", "Others", "Monolithic"]] = Field(default=None)
    EMERGENCYSTATE_MODE: Optional[Literal["No", "Yes"]] = Field(default=None)

    # Numériques Optionnelles
    AMT_GOODS_PRICE: Optional[float] = Field(default=None, ge=0)
    OWN_CAR_AGE: Optional[float] = Field(default=None, ge=0)
    EXT_SOURCE_1: Optional[float] = Field(default=None, ge=0)
    EXT_SOURCE_2: Optional[float] = Field(default=None, ge=0)
    EXT_SOURCE_3: Optional[float] = Field(default=None, ge=0)
    APARTMENTS_AVG: Optional[float] = Field(default=None, ge=0)
    BASEMENTAREA_AVG: Optional[float] = Field(default=None, ge=0)
    YEARS_BEGINEXPLUATATION_AVG: Optional[float] = Field(default=None, ge=0)
    YEARS_BUILD_AVG: Optional[float] = Field(default=None, ge=0)
    COMMONAREA_AVG: Optional[float] = Field(default=None, ge=0)
    ELEVATORS_AVG: Optional[float] = Field(default=None, ge=0)
    ENTRANCES_AVG: Optional[float] = Field(default=None, ge=0)
    FLOORSMAX_AVG: Optional[float] = Field(default=None, ge=0)
    FLOORSMIN_AVG: Optional[float] = Field(default=None, ge=0)
    LANDAREA_AVG: Optional[float] = Field(default=None, ge=0)
    LIVINGAPARTMENTS_AVG: Optional[float] = Field(default=None, ge=0)
    LIVINGAREA_AVG: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAPARTMENTS_AVG: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAREA_AVG: Optional[float] = Field(default=None, ge=0)
    APARTMENTS_MODE: Optional[float] = Field(default=None, ge=0)
    BASEMENTAREA_MODE: Optional[float] = Field(default=None, ge=0)
    YEARS_BEGINEXPLUATATION_MODE: Optional[float] = Field(default=None, ge=0)
    YEARS_BUILD_MODE: Optional[float] = Field(default=None, ge=0)
    COMMONAREA_MODE: Optional[float] = Field(default=None, ge=0)
    ELEVATORS_MODE: Optional[float] = Field(default=None, ge=0)
    ENTRANCES_MODE: Optional[float] = Field(default=None, ge=0)
    FLOORSMAX_MODE: Optional[float] = Field(default=None, ge=0)
    FLOORSMIN_MODE: Optional[float] = Field(default=None, ge=0)
    LANDAREA_MODE: Optional[float] = Field(default=None, ge=0)
    LIVINGAPARTMENTS_MODE: Optional[float] = Field(default=None, ge=0)
    LIVINGAREA_MODE: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAPARTMENTS_MODE: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAREA_MODE: Optional[float] = Field(default=None, ge=0)
    APARTMENTS_MEDI: Optional[float] = Field(default=None, ge=0)
    BASEMENTAREA_MEDI: Optional[float] = Field(default=None, ge=0)
    YEARS_BEGINEXPLUATATION_MEDI: Optional[float] = Field(default=None, ge=0)
    YEARS_BUILD_MEDI: Optional[float] = Field(default=None, ge=0)
    COMMONAREA_MEDI: Optional[float] = Field(default=None, ge=0)
    ELEVATORS_MEDI: Optional[float] = Field(default=None, ge=0)
    ENTRANCES_MEDI: Optional[float] = Field(default=None, ge=0)
    FLOORSMAX_MEDI: Optional[float] = Field(default=None, ge=0)
    FLOORSMIN_MEDI: Optional[float] = Field(default=None, ge=0)
    LANDAREA_MEDI: Optional[float] = Field(default=None, ge=0)
    LIVINGAPARTMENTS_MEDI: Optional[float] = Field(default=None, ge=0)
    LIVINGAREA_MEDI: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAPARTMENTS_MEDI: Optional[float] = Field(default=None, ge=0)
    NONLIVINGAREA_MEDI: Optional[float] = Field(default=None, ge=0)
    TOTALAREA_MODE: Optional[float] = Field(default=None, ge=0)
    OBS_30_CNT_SOCIAL_CIRCLE: Optional[float] = Field(default=None, ge=0)
    DEF_30_CNT_SOCIAL_CIRCLE: Optional[float] = Field(default=None, ge=0)
    OBS_60_CNT_SOCIAL_CIRCLE: Optional[float] = Field(default=None, ge=0)
    DEF_60_CNT_SOCIAL_CIRCLE: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_HOUR: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_DAY: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_WEEK: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_MON: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_QRT: Optional[float] = Field(default=None, ge=0)
    AMT_REQ_CREDIT_BUREAU_YEAR: Optional[float] = Field(default=None, ge=0)