name: Python Tests

# Quand est-ce que ce workflow se lance ?
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    # On utilise une machine virtuelle Ubuntu (Linux)
    runs-on: ubuntu-latest

    steps:
    # 1. On récupère notre code sur la machine
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0 # <-- on copie tout l'historique git (pour éviter l'erreur shallow clone)
    # 2. On installe Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3. On installe Poetry (ton gestionnaire de paquets)
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    # 4. On installe toutes les dépendances (y compris pytest et httpx)
    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    # 5. LE MOMENT DE VÉRITÉ : On lance pytest
    - name: Run tests
      run: poetry run pytest tests/

# --- ÉTAPE DOCKER ---
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # On ne veut pas l'envoyer sur un registre, juste tester le build
        tags: credit-api:latest

# --- DÉPLOIEMENT SUR HUGGING FACE ---
    - name: Push to Hugging Face Spaces
      env:
        # On récupère le mot de passe dans le coffre-fort de GitHub
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        # On ajoute Hugging Face comme destination
        git remote add space https://apinsun:$HF_TOKEN@huggingface.co/spaces/apinsun/Projet8
        
        # On force l'envoi de la branche principale
        git push --force space main
